### ISSUE TITLE
Unhandled Exception: PlatformException(Bluetooth is not available, , null, null)

### ISSUE THREAD

**Issue by Finnomator** [Finnomator/robi_line_drawer#21]
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(Bluetooth is not available, , null, null)
#0      UniversalBlePlatformChannel.stopScan (package:universal_ble/src/universal_ble_pigeon/universal_ble.g.dart:369:7)
<asynchronous suspension>
#1      _QueuedFuture.execute (package:universal_ble/src/queue.dart:67:18)
<asynchronous suspension>
```

**Comment by Finnomator** [comment]
Bluetooth is currently not supported.
